// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PostHistory struct {
	ID        int32
	UserID    pgtype.Int4
	Uri       string
	Hashtags  []string
	CreatedAt pgtype.Timestamptz
}

type Template struct {
	ID        int32
	UserID    pgtype.Int4
	Name      string
	Suffix    string
	Position  pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int32
	Did          string
	Handle       pgtype.Text
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Plan         string
	Theme        string
}
