// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (user_id, name, suffix, position)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, suffix, position, created_at
`

type CreateTemplateParams struct {
	UserID   pgtype.Int4
	Name     string
	Suffix   string
	Position pgtype.Int4
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.UserID,
		arg.Name,
		arg.Suffix,
		arg.Position,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Suffix,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND user_id = $2
`

type DeleteTemplateParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.UserID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, user_id, name, suffix, position, created_at FROM templates WHERE id = $1 AND user_id = $2
`

type GetTemplateParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.UserID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Suffix,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listTemplatesByUser = `-- name: ListTemplatesByUser :many
SELECT id, user_id, name, suffix, position, created_at FROM templates
WHERE user_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListTemplatesByUser(ctx context.Context, userID pgtype.Int4) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Suffix,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name   = $3,
    suffix = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, suffix, position, created_at
`

type UpdateTemplateParams struct {
	ID     int32
	UserID pgtype.Int4
	Name   string
	Suffix string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Suffix,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Suffix,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateTemplatePosition = `-- name: UpdateTemplatePosition :one
UPDATE templates
SET position = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, suffix, position, created_at
`

type UpdateTemplatePositionParams struct {
	ID       int32
	UserID   pgtype.Int4
	Position pgtype.Int4
}

func (q *Queries) UpdateTemplatePosition(ctx context.Context, arg UpdateTemplatePositionParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplatePosition, arg.ID, arg.UserID, arg.Position)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Suffix,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
