// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentTagsByUser = `-- name: GetRecentTagsByUser :many
SELECT tag::text AS tag, MAX(ph.created_at) AS last_used
FROM post_history ph, unnest(ph.hashtags) AS tag
WHERE ph.user_id = $1
GROUP BY tag
ORDER BY last_used DESC
LIMIT 10
`

type GetRecentTagsByUserRow struct {
	Tag      string
	LastUsed interface{}
}

func (q *Queries) GetRecentTagsByUser(ctx context.Context, userID pgtype.Int4) ([]GetRecentTagsByUserRow, error) {
	rows, err := q.db.Query(ctx, getRecentTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTagsByUserRow
	for rows.Next() {
		var i GetRecentTagsByUserRow
		if err := rows.Scan(&i.Tag, &i.LastUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDID = `-- name: GetUserByDID :one
SELECT id, did, handle, access_token, refresh_token, token_expiry, created_at, plan, theme FROM users WHERE did = $1
`

func (q *Queries) GetUserByDID(ctx context.Context, did string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDID, did)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Handle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.Plan,
		&i.Theme,
	)
	return i, err
}

const updateUserTokens = `-- name: UpdateUserTokens :one
UPDATE users
SET access_token  = $2,
    refresh_token = $3,
    token_expiry  = $4
WHERE did = $1
RETURNING id, did, handle, access_token, refresh_token, token_expiry, created_at, plan, theme
`

type UpdateUserTokensParams struct {
	Did          string
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamptz
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTokens,
		arg.Did,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Handle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.Plan,
		&i.Theme,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (did, handle, access_token, refresh_token, token_expiry)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (did) DO UPDATE SET
    handle        = EXCLUDED.handle,
    access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    token_expiry  = EXCLUDED.token_expiry
RETURNING id, did, handle, access_token, refresh_token, token_expiry, created_at, plan, theme
`

type UpsertUserParams struct {
	Did          string
	Handle       pgtype.Text
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamptz
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Did,
		arg.Handle,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Handle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.Plan,
		&i.Theme,
	)
	return i, err
}
